[versions]
libautoupdate = "1.3.1"
moulconfig = "1.3.0"

[libraries]
moulconfig = { module = "org.notenoughupdates.moulconfig:MoulConfig", version.ref = "moulconfig" }
libautoupdate = { module = "moe.nea:libautoupdate", version.ref = "libautoupdate" }