[versions]
moulconfig = "1.3.0"
modrinthautoupdater = "1.1.1"

[libraries]
moulconfig = { module = "org.notenoughupdates.moulconfig:MoulConfig", version.ref = "moulconfig" }
modrinthautoupdater = { module = "com.github.ChindeaYTB:modrinthautoupdater", version.ref = "modrinthautoupdater" }