[versions]
moulconfig = "1.3.0"
#modrinthautoupb = "1.0.0"

[libraries]
moulconfig = { module = "org.notenoughupdates.moulconfig:MoulConfig", version.ref = "moulconfig" }
#modrinthautoupb = { module = "northing yet", version.ref = "modrinthautoupb" }